# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailthemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themesettings',
            options={'verbose_name': 'themes', 'verbose_name_plural': 'themes'},
        ),
    ]
