name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./src

jobs:
  setup-and-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          path: ./src
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
           python-version: '3.9'
      - name: Install python dependencies
        run: |
          make install
      - name: Lint with flake8
        run: |
          flake8 .

  run-tests:
    needs: setup-and-linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        django-version: [3.1, 3.2]
        wagtail-version: [2.12, 2.13]
        exclude:
          - django-version: 3.2
            wagtail-version: 2.12
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          path: ./src
      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          make install
      - name: Install specific matrix dependencies
        run: |
          pip install "wagtail~=${{ matrix.wagtail-version }}.0" "django~=${{ matrix.django-version }}.0"
          pip list
      - name: Run the testsuite
        run: |
          pytest
