name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./src

jobs:
  setup-and-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          path: ./src
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
           python-version: '3.11'
      - name: Install python dependencies
        run: |
          make install
      - name: Lint with flake8
        run: |
          flake8 .

  run-tests:
    needs: setup-and-linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        django-version: [3.2, 4.1, 4.2]
        wagtail-version: [3, 4.2, 5]
        exclude:
          - wagtail-version: 3
            django-version: 4.1
          - wagtail-version: 3
            django-version: 4.2
          - wagtail-version: 4.2
            django-version: 4.2
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          path: ./src
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          make install
      - name: Install specific matrix dependencies
        run: |
          pip install "wagtail~=${{ matrix.wagtail-version }}.0" "django~=${{ matrix.django-version }}.0"
          pip list
      - name: Run the testsuite
        run: |
          pytest
